const ko = {
  eyebrow: "ARTLINK REHEARSAL", title: "대사 연습실", intro: "당신의 언어로.\n당신의 장면을.", introBody: "상대 대사를 듣고, 내 차례에 말하세요.",
  back: "‹ 뒤로", scriptLanguage: "대사 언어", feedbackLanguage: "설명 · 피드백 언어", languageHint: "앱 언어는 그대로 유지됩니다.", korean: "한국어", english: "English", scenes: "연습 장면", sceneCount: "{{count}}개의 장면", lines: "{{count}}줄", original: "ARTLINK ORIGINAL", source: "장면 출처", privateLabel: "비공개 · 이 화면에서만 보관",
  pasteTitle: "내 대본으로 연습", pasteBody: "두 배역의 대사를 붙여넣고 시작하세요.", pasteOpen: "대본 붙여넣기", pastePlaceholder: "ALEX: I thought you had left.\nMAYA: I came back for the key.", pasteFormat: "한 줄에 하나의 대사를 ‘배역 이름: 대사’로 적어주세요. 두 배역, 최대 120줄 · 12,000자까지 가능합니다.", pastePrivacy: "붙여넣은 대본은 이 화면에서만 사용하며 원문을 업로드하지 않습니다. 기기 음성의 네트워크 사용 여부는 기기 설정에 따릅니다.", pasteVerify: "배역과 대사 확인", pasteCancel: "닫기", confirmTitle: "이 배역이 맞나요?", confirmBody: "{{roles}} · {{count}}줄\n확인 후 내 배역을 고를 수 있습니다.", confirmUse: "이 대본으로 연습", edit: "다시 편집", empty: "대사를 붙여넣어주세요.", tooLong: "대본은 12,000자 이내로 나누어 넣어주세요.", tooManyLines: "한 장면은 120줄 이내로 나누어 넣어주세요.", twoRoles: "서로 다른 두 배역의 대사가 필요합니다. 이름 표기를 일치시켜주세요.", format: "{{line}}번째 줄을 ‘배역 이름: 대사’로 확인해주세요. 배역은 40자, 대사는 한 줄에 1,000자까지 가능합니다.",
  myRole: "내 배역", situation: "장면의 상황", objective: "이번에 시도할 것", voiceLabel: "상대역 영어 음성", voiceUS: "미국 영어", voiceUK: "영국 영어", voiceHint: "기기 음성으로 읽습니다. 자동 차례 감지 없이 ‘다음’으로 넘깁니다.", cue: "🎬 큐 연습", cueBody: "한 줄씩 듣고 말하며 연습해요. 내 대사는 탭해서 확인할 수 있습니다.", script: "📜 대본 보기", scriptBody: "장면 전체를 읽고, 내 대사를 가리며 암기를 확인합니다.", practiceTools: "연습 도구", partnerVoice: "🔊 상대 대사 음성", mine: " (나)", hidden: "내 차례예요. 기억나는 대로 말해보고,\n탭하면 대사를 확인할 수 있어요.", previous: "이전", next: "다음", skipNext: "건너뛰고 다음", end: "끝", restart: "처음부터", note: "연습 기록 남기기", noteTitle: "{{play}} 2인 대사", finish: "연습 끝", hideLines: "내 대사 가리기 ({{role}})", masked: "● ● ●  (탭해서 확인)", scriptHeader: "{{play}} · 대본", cueHeader: "{{play}} · {{role}} 역", progress: "{{current}} / {{total}}", recordPreparing: "녹음 준비 중…", recorded: "녹음 {{count}}개 보관 중", readyNote: "기록에 이어서 저장할 수 있습니다. AI 분석은 자동으로 실행되지 않습니다.",
  rightsOriginal: "아트링크를 위해 만든 오리지널 연습 장면입니다. 다른 작품의 대사를 발췌하지 않았습니다.", rightsSource: "ACT RAW 제공 장면 · 고전 각색과 오리지널 장면이 포함됩니다. 외부 공연·출판·공개 제출 전에는 해당 장면과 번역의 이용 조건을 확인하세요.", rightsPrivate: "직접 넣은 비공개 대본입니다. 이용 권한이 있는 자료로 연습해주세요.", noScenes: "이 언어의 장면을 준비하고 있습니다.", englishDescriptionNotice: "이 장면의 설명과 배역 이름은 원문 한국어로 제공됩니다.",
};
const en = {
  eyebrow: "ARTLINK REHEARSAL", title: "Rehearsal studio", intro: "Your language.\nYour scene.", introBody: "Listen to your partner, then take your turn.",
  back: "‹ Back", scriptLanguage: "Script language", feedbackLanguage: "Guidance & feedback language", languageHint: "Your app language stays the same.", korean: "한국어", english: "English", scenes: "Practice scenes", sceneCount: "{{count}} scenes", lines: "{{count}} lines", original: "ARTLINK ORIGINAL", source: "Scene source", privateLabel: "Private · kept on this screen only",
  pasteTitle: "Bring your own script", pasteBody: "Paste a two-person scene to rehearse.", pasteOpen: "Paste a script", pastePlaceholder: "ALEX: I thought you had left.\nMAYA: I came back for the key.", pasteFormat: "Use one ‘ROLE: dialogue’ per line. Exactly two roles, up to 120 lines and 12,000 characters.", pastePrivacy: "Pasted text stays on this screen and is not uploaded. Device speech may use a network depending on your device settings.", pasteVerify: "Check roles & lines", pasteCancel: "Close", confirmTitle: "Are these the right roles?", confirmBody: "{{roles}} · {{count}} lines\nChoose your role on the next screen.", confirmUse: "Rehearse this script", edit: "Edit again", empty: "Paste your dialogue first.", tooLong: "Split your script into sections of 12,000 characters or fewer.", tooManyLines: "Split your scene into 120 lines or fewer.", twoRoles: "Include dialogue for exactly two roles. Keep each role’s name consistent.", format: "Check line {{line}}: use ‘ROLE: dialogue’. Role names can be up to 40 characters, and each line up to 1,000.",
  myRole: "Your role", situation: "The situation", objective: "A choice to explore", voiceLabel: "Partner’s English voice", voiceUS: "US English", voiceUK: "UK English", voiceHint: "Uses your device’s voice. Tap Next to advance; turns are not detected automatically.", cue: "🎬 Cue practice", cueBody: "Listen and respond one line at a time. Tap to reveal your lines.", script: "📜 Read the script", scriptBody: "See the whole scene, or hide your lines to check your memory.", practiceTools: "Practice tools", partnerVoice: "🔊 Partner voice", mine: " (you)", hidden: "Your turn. Try the line from memory.\nTap to reveal it when you need it.", previous: "Previous", next: "Next", skipNext: "Skip & next", end: "End", restart: "Restart", note: "Save practice notes", noteTitle: "{{play}} · rehearsal", finish: "Finish practice", hideLines: "Hide my lines ({{role}})", masked: "● ● ●  (tap to reveal)", scriptHeader: "{{play}} · Script", cueHeader: "{{play}} · {{role}}", progress: "{{current}} / {{total}}", recordPreparing: "Preparing recorder…", recorded: "{{count}} recording(s) kept", readyNote: "Continue to save your notes. AI analysis will only run when you request it.",
  rightsOriginal: "An original practice scene created for ArtLink. It does not quote a third-party script.", rightsSource: "Scenes supplied by ACT RAW include adaptations and original work. Check the scene and translation’s terms before public performance, publication, or submission.", rightsPrivate: "Your private script. Please use material you have permission to rehearse.", noScenes: "Scenes in this language are coming soon.", englishDescriptionNotice: "This scene’s description and character names are provided in the original Korean.",
};
export default { ko: { duetStudio: ko }, en: { duetStudio: en } };
