export default {
  ko: { opportunities: {
    title: "공고·기회", eyebrow: "YOUR NEXT OPPORTUNITY", headline: "다음 작품으로 이어지는 기회", subtitle: "조건을 확인하고, 지원할 작품을 준비하세요.",
    latest: "최신", deadline_view: "마감순", saved: "저장", save: "저장하기", unsave: "저장 해제", filters: "조건", reset: "초기화", done: "조건 적용",
    search: "작품명, 공고, 키워드 검색", source: "등록 경로", source_all: "전체", source_ai: "수집 공고", source_user: "직접 등록 · 마감 포함", category: "유형", field: "분야",
    region: "국가·지역", region_placeholder: "예: 서울, London", language: "언어", language_placeholder: "공고에 명시된 언어", pay: "보수", paid_only: "유급 확인", remote_only: "원격 가능 확인", remote: "진행 방식", remote_yes: "원격 가능", remote_no: "현장 참여", unspecified: "미기재",
    location: "국가·지역", deadline: "마감", materials: "제출물", materials_unknown: "제출물 미기재 · 원문에서 확인하세요", application: "지원 방법", route_ready: "지원처 있음", route_source: "원문에서 지원처 확인", route_unknown: "지원처 확인 필요",
    field_match: "내 관심 분야", region_match: "선택한 지역 일치", language_match: "선택한 언어 일치", known_conditions: "확인된 조건", facts_notice: "공고에 명시된 정보만 표시합니다. 세부 자격과 제출물은 원문을 확인하세요.",
    empty_title: "조건에 맞는 공고가 없습니다", empty_body: "언어·보수·원격 정보가 미기재인 공고는 해당 조건에서 제외됩니다. 조건을 줄이거나 공고를 더 불러오세요.", saved_empty: "지원하고 싶은 공고를 모아보세요", saved_empty_body: "공고의 저장 버튼을 누르면 이 기기에 보관됩니다.", snapshot_notice: "저장한 공고는 이 기기의 보관본입니다. 지원 전 원문에서 마감과 변경사항을 확인하세요.",
    loaded_count: "불러온 공고 {{count}}개", partial_notice: "검색·마감순·조건은 불러온 공고에 적용됩니다.", load_more: "공고 더 불러오기", loading: "공고를 불러오는 중", error: "공고를 불러오지 못했습니다", retry: "다시 시도", save_error: "저장하지 못했습니다. 다시 시도해 주세요.", saved_error: "저장한 공고를 읽지 못했습니다. 다시 시도해 주세요.", register: "공고 등록", detail: "자세히 보기", prepare: "지원 준비하기", prepare_notice: "작품과 제출물을 준비하는 기록을 만듭니다. 실제 지원은 지원처에서 완료해 주세요.",
    preparation_title: "지원 준비 · {{title}}", check_original: "원문에서 지원 자격과 최신 마감일 확인", prepare_work: "제출할 작품·영상·포트폴리오 준비", review_then_apply: "제출물을 검토한 뒤 안내된 지원처에서 직접 지원", closed_prepare: "마감된 공고입니다", requirements_unknown: "상세 자격은 원문에서 확인하세요", back: "뒤로", manage: "공고 관리", saved_count: "저장 {{count}}", contact: "지원처", sign_in_save: "계정 준비 후 다시 저장해 주세요.",
  } },
  en: { opportunities: {
    title: "Opportunities", eyebrow: "YOUR NEXT OPPORTUNITY", headline: "A place for your next work", subtitle: "Check the details. Prepare something worth sharing.",
    latest: "Latest", deadline_view: "Deadline", saved: "Saved", save: "Save", unsave: "Unsave", filters: "Filters", reset: "Reset", done: "Apply filters",
    search: "Search titles, opportunities, keywords", source: "Listing source", source_all: "All", source_ai: "Collected", source_user: "Member posts · includes closed", category: "Type", field: "Discipline",
    region: "Country / location", region_placeholder: "e.g. Seoul, London", language: "Language", language_placeholder: "Language specified in the listing", pay: "Pay", paid_only: "Paid confirmed", remote_only: "Remote confirmed", remote: "Work format", remote_yes: "Remote available", remote_no: "In person", unspecified: "Not specified",
    location: "Country / location", deadline: "Deadline", materials: "Materials", materials_unknown: "Not specified — check the original listing", application: "How to apply", route_ready: "Application contact listed", route_source: "Check original for application", route_unknown: "Application details needed",
    field_match: "Your discipline", region_match: "Selected location matches", language_match: "Selected language matches", known_conditions: "Listed details", facts_notice: "Only stated information is shown. Check the original for eligibility and required materials.",
    empty_title: "No listings match these filters", empty_body: "Listings without language, pay or remote details are excluded by those filters. Adjust your filters or load more listings.", saved_empty: "Keep opportunities you care about", saved_empty_body: "Tap Save on a listing to keep it on this device.", snapshot_notice: "Saved listings are copies on this device. Check the original for deadlines and changes before applying.",
    loaded_count: "{{count}} listings loaded", partial_notice: "Search, deadline order and filters apply to loaded listings.", load_more: "Load more listings", loading: "Loading opportunities", error: "Could not load opportunities", retry: "Try again", save_error: "Could not save. Please try again.", saved_error: "Could not read saved listings. Please try again.", register: "Post a listing", detail: "View details", prepare: "Prepare application", prepare_notice: "Create a record to prepare your work and materials. Complete the application at the listed destination.",
    preparation_title: "Application preparation · {{title}}", check_original: "Check eligibility and the latest deadline in the original listing", prepare_work: "Prepare the required work, video or portfolio", review_then_apply: "Review your materials, then apply at the listed destination", closed_prepare: "This listing is closed", requirements_unknown: "Check the original for full eligibility details", back: "Back", manage: "Manage listing", saved_count: "{{count}} saved", contact: "Application contact", sign_in_save: "Please wait for your account to be ready and try again.",
  } },
};
